version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - /alert_generator
      - /promql
      - /promqle2e
      - /remotewrite/receiver
      - /remotewrite/sender
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Exclude configs synced from upstream prometheus/prometheus.
    exclude-paths:
      - .github/workflows/container_description.yml
      - .github/workflows/golangci-lint.yml
