version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  exclusions:
    generated: lax
